image: golang:1.14

variables:
  ARTIFACT_DIRECTORY: buildOutput
  BINARY_NAME: strict

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/
    - ${GOPATH}/bin/

before_script:
  - go get -d -v all
  - go install ./cmd/strict_sdk

stages:
  - build
  - bundle-sdk
  - test

test:
  stage: test
  script:
    - go test -v -cover ./...
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull

.build:
  stage: build

build:windows:
  stage: build
  extends: .build
  script:
    - env GOOS=windows GOARCH=amd64 go build -o ${CI_PROJECT_DIR}/${ARTIFACT_DIRECTORY}/${BINARY_NAME} ./cmd/strict
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull-push
  artifacts:
    name: strict-sdk-bundlers-windows
    paths:
      - ${CI_PROJECT_DIR}/${ARTIFACT_DIRECTORY}/${BINARY_NAME}

build:linux:
  stage: build
  extends: .build
  script:
    - env GOOS=linux GOARCH=amd64 go build -o ${CI_PROJECT_DIR}/${ARTIFACT_DIRECTORY}/${BINARY_NAME} ./cmd/strict
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull-push
  artifacts:
    name: strict-sdk-bundlers-linux
    paths:
      - ${CI_PROJECT_DIR}/${ARTIFACT_DIRECTORY}/${BINARY_NAME}

build:osx:
  stage: build
  extends: .build
  script:
    - env GOOS=darwin GOARCH=amd64 go build -o ${CI_PROJECT_DIR}/${ARTIFACT_DIRECTORY}/${BINARY_NAME} ./cmd/strict
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull-push
  artifacts:
    name: strict-sdk-bundlers-osx
    paths:
      - ${CI_PROJECT_DIR}/${ARTIFACT_DIRECTORY}/${BINARY_NAME}

.bundle-sdk:
  stage: bundle-sdk
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull

bundle-sdk:windows:
  stage: bundle-sdk
  extends: .bundle-sdk
  script:
    - strict_sdk make -p windows -v ${CI_COMMIT_REF_SLUG} -b -o output -e ${CI_PROJECT_DIR}/${ARTIFACT_DIRECTORY}/${BINARY_NAME}
  artifacts:
    name: sdk-${CI_COMMIT_REF_SLUG}-windows-x86_64.tar.gz
    paths:
      - output
  dependencies:
    - build:windows

bundle-sdk:linux:
  stage: bundle-sdk
  extends: .bundle-sdk
  script:
    - strict_sdk make -p linux -v ${CI_COMMIT_REF_SLUG} -b -o output -e ${CI_PROJECT_DIR}/${ARTIFACT_DIRECTORY}/${BINARY_NAME}
  artifacts:
    name: sdk-${CI_COMMIT_REF_SLUG}-linux-x86_64.tar.gz
    paths:
      - output
  dependencies:
    - build:linux

bundle-sdk:osx:
  stage: bundle-sdk
  extends: .bundle-sdk
  script:
    - strict_sdk make -p osx -v ${CI_COMMIT_REF_SLUG} -b -o output -e ${CI_PROJECT_DIR}/${ARTIFACT_DIRECTORY}/${BINARY_NAME}
  artifacts:
    name: sdk-${CI_COMMIT_REF_SLUG}-osx-x86_64.tar.gz
    paths:
      - output
  dependencies:
    - build:osx