image: golang:1.14

variables:
  ARTIFACT_DIRECTORY: buildOutput
  BINARY_NAME: strict

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/
    - ${GOPATH}/bin/

before_script:
  - go get -d -v all

stages:
  - build
  - test

build:
  stage: build
  script:
    - go build -o ${CI_PROJECT_DIR}/${ARTIFACT_DIRECTORY}/${BINARY_NAME} ./cmd/strict
  artifacts:
    paths:
      - ${ARTIFACTS_DIRECTORY}/${BINARY_NAME}
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull-push

test:
  stage: test
  script:
    - go test -v -cover ./...
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull