<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>strict</string>
   </array>
  <key>name</key>
  <string>strict</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.strict</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#method</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#method_call</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#assignment</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#loops</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(do|method|and|or|in|is|from|downto|return|to|type|for|if|else|yield|isnt|not)(\s|\Z)</string>
          <key>name</key>
          <string>keyword.strict</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#identifier</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#operator</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.strict</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\&quot;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.strict</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.strict</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.strict</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\&lt;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.strict</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__3</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\&gt;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.strict</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#multi_line_comment</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(//.*)</string>
          <key>name</key>
          <string>comment.strict</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\s])</string>
          <key>name</key>
          <string>invalid.strict</string>
        </dict>
       </array>
    </dict>
    <key>assignment</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>([a-zA-Z]+[a-zA-Z0-9_]*)(\s*)(\=)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>variable.strict</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>whitespace.strict</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>punctuation.strict</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>expression</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#identifier</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#operator</string>
        </dict>
       </array>
    </dict>
    <key>identifier</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>([a-zA-Z]([a-zA-Z0-9]*))</string>
          <key>name</key>
          <string>entity.name.strict</string>
        </dict>
       </array>
    </dict>
    <key>loops</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(for)(\s+)([a-zA-Z]+[a-zA-Z0-9_]*)(\s+)(from)(\s+)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.strict</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>whitespace.strict</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>variable.strict</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>whitespace.strict</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>keyword.strict</string>
            </dict>
            <key>6</key>
            <dict>
              <key>name</key>
              <string>whitespace.strict</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#loops__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(do)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.strict</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(for)(\s+)([a-zA-Z]+[a-zA-Z0-9_]*)(\s+)(in)(\s+)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.strict</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>whitespace.strict</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>variable.strict</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>whitespace.strict</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>keyword.strict</string>
            </dict>
            <key>6</key>
            <dict>
              <key>name</key>
              <string>whitespace.strict</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#loops__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(do)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.strict</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>loops__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>loops__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\\(?:\\|&quot;))</string>
          <key>name</key>
          <string>string.strict</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\x{0022}\x{005c}]+)</string>
          <key>name</key>
          <string>string.strict</string>
        </dict>
       </array>
    </dict>
    <key>main__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#expression</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(,)</string>
          <key>name</key>
          <string>punctuation.strict</string>
        </dict>
       </array>
    </dict>
    <key>main__3</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#identifier</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(,)</string>
          <key>name</key>
          <string>punctuation.strict</string>
        </dict>
       </array>
    </dict>
    <key>method</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(method)(\s+)([\w\x{003c}\x{003e}]+)(\s+)([a-zA-Z]+[a-zA-Z0-9_]*)(\s*)(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.strict</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>whitespace.strict</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.strict</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>whitespace.strict</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.strict</string>
            </dict>
            <key>6</key>
            <dict>
              <key>name</key>
              <string>whitespace.strict</string>
            </dict>
            <key>7</key>
            <dict>
              <key>name</key>
              <string>punctuation.strict</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#method__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.strict</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>method__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\,)</string>
          <key>name</key>
          <string>punctuation.strict</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([\w\x{003c}\x{003e}]+)(\s+)(\w+)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.strict</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>whitespace.strict</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>variable.parameter.strict</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>([\w\x{003c}\x{003e}]+)</string>
          <key>name</key>
          <string>variable.parameter.strict</string>
        </dict>
       </array>
    </dict>
    <key>method_call</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>([a-zA-Z]+[a-zA-Z0-9_]*)(\s*)(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.strict</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.strict</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>punctuation.strict</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#method_call__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.strict</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>method_call__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(,)</string>
          <key>name</key>
          <string>punctuation.strict</string>
        </dict>
       </array>
    </dict>
    <key>multi_line_comment</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(/\*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.strict</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>comment.strict</string>
          <key>end</key>
          <string>(\*/)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.strict</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>multi_line_comment__1</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>numeric</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\b\d+)</string>
          <key>name</key>
          <string>constant.numeric.strict</string>
        </dict>
       </array>
    </dict>
    <key>operator</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>([\x{002b}\x{007c}\-\x{0028}\x{0029}\x{003c}\x{003e}\[\]\x{0021}\x{003d}\x{0025}\x{002a}\x{002c}]+)</string>
          <key>name</key>
          <string>punctuation.strict</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>

