<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array>
    <string>strict</string>
   </array>
  <key>name</key>
  <string>strict</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.strict</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#TopLevelDeclarations</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#Code</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\s])</string>
          <key>name</key>
          <string>invalid.strict</string>
        </dict>
       </array>
    </dict>
    <key>Assignment</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>([a-zA-Z]+[a-zA-Z0-9_]*)(\s*)(\=)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>variable.strict</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>none.strict</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>punctuation.strict</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>Code</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#Comment</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#Statements</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#Expressions</string>
        </dict>
       </array>
    </dict>
    <key>Comment</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(//.*)</string>
          <key>name</key>
          <string>comment.line.strict</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(/\*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.line.strict</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>comment.line.strict</string>
          <key>end</key>
          <string>(\*/)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.line.strict</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>Comment__1</key>
    <dict>
      <key>patterns</key>
      <array>
       </array>
    </dict>
    <key>CreateExpression</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>(create)(\s+)([a-zA-Z]+[a-zA-Z0-9_]*)(\s*)(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.other.strict</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>none.strict</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.strict</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>punctuation.strict</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>punctuation.strict</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#CreateExpression__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.strict</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>CreateExpression__1</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>([a-zA-Z]+[a-zA-Z0-9_]*)(\s*)(\:)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.other.attribute-name.strict</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>none.strict</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>punctuation.strict</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(,)</string>
          <key>name</key>
          <string>punctuation.strict</string>
        </dict>
       </array>
    </dict>
    <key>ExpressionList</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.strict</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#ExpressionList__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.strict</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>ExpressionList__1</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#ExpressionList</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(,)</string>
          <key>name</key>
          <string>punctuation.strict</string>
        </dict>
       </array>
    </dict>
    <key>Expressions</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#CreateExpression</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#Keyword</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#MethodCall</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\.)([a-zA-Z]+[a-zA-Z0-9_]*)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.strict</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>variable.field.strict</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>([\w\x{003c}\x{003e}]+)(\s+)([a-zA-Z]+[a-zA-Z0-9_]*)(\s+)(=)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.strict</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>none.strict</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>variable.strict</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>none.strict</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>punctuation.strict</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>([\w\x{003c}\x{003e}]+)(\s+)([a-zA-Z]+[a-zA-Z0-9_]*)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.strict</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>none.strict</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>variable.strict</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#ExpressionList</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#Operator</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#Assignment</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#Identifier</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#NumberLiteral</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#TextLiteral</string>
        </dict>
       </array>
    </dict>
    <key>ForEachLoop</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>(for)(\s+)([a-zA-Z]+[a-zA-Z0-9_]*)(\s+)(in)(\s+)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.control.strict</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>none.strict</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>variable.strict</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>none.strict</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>keyword.control.strict</string>
            </dict>
            <key>6</key>
            <dict>
              <key>name</key>
              <string>none.strict</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#ForEachLoop__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(do)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.control.strict</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>ForEachLoop__1</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#Code</string>
        </dict>
       </array>
    </dict>
    <key>FromToLoop</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>(for)(\s+)([a-zA-Z]+[a-zA-Z0-9_]*)(\s+)(from)(\s+)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.control.strict</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>none.strict</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>variable.strict</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>none.strict</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>keyword.control.strict</string>
            </dict>
            <key>6</key>
            <dict>
              <key>name</key>
              <string>none.strict</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#FromToLoop__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(do)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.control.strict</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>FromToLoop__1</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#Code</string>
        </dict>
       </array>
    </dict>
    <key>Identifier</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(true|false|absent|this)</string>
          <key>name</key>
          <string>variable.language.strict</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([a-zA-Z][a-zA-Z0-9]*)</string>
          <key>name</key>
          <string>variable.strict</string>
        </dict>
       </array>
    </dict>
    <key>Keyword</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(^|\B) (continue|break|do|in|from|downto|return|to|for|if|else|yield)(\S|$)</string>
          <key>name</key>
          <string>keyword.control.strict</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(import|as|assert|test|create|throw|try|method|is|isnt|not)</string>
          <key>name</key>
          <string>keyword.other.strict</string>
        </dict>
       </array>
    </dict>
    <key>Loops</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#ForEachLoop</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#FromToLoop</string>
        </dict>
       </array>
    </dict>
    <key>MethodCall</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>(.)([a-zA-Z]+[a-zA-Z0-9_]*)(\s*)(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.strict</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>meta.function-call.strict</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>punctuation.strict</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>punctuation.strict</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#MethodCall__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.strict</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>([a-zA-Z]+[a-zA-Z0-9_]*)(\s*)(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>meta.function-call.strict</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.strict</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>punctuation.strict</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#MethodCall__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.strict</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>MethodCall__1</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(,)</string>
          <key>name</key>
          <string>punctuation.strict</string>
        </dict>
       </array>
    </dict>
    <key>MethodCall__2</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(,)</string>
          <key>name</key>
          <string>punctuation.strict</string>
        </dict>
       </array>
    </dict>
    <key>MethodDeclaration</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>(method)(\s+)(?:(?:([\w\x{003c}\x{003e}]+)(\s+))?)([a-zA-Z]+[a-zA-Z0-9_]*)(\s*)(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.declaration.strict</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>none.strict</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.strict</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>none.strict</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.strict</string>
            </dict>
            <key>6</key>
            <dict>
              <key>name</key>
              <string>none.strict</string>
            </dict>
            <key>7</key>
            <dict>
              <key>name</key>
              <string>punctuation.strict</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#MethodDeclaration__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.strict</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(method)(\s+)(?:([\w\x{003c}\x{003e}]+)?)(\s+)([a-zA-Z]+[a-zA-Z0-9_]*)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.declaration.strict</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>none.strict</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.strict</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>none.strict</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.strict</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(method)(\s+)([a-zA-Z]+[a-zA-Z0-9_]*)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.declaration.strict</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>none.strict</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.strict</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(method)(\s+)([\w\x{003c}\x{003e}]+)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.declaration.strict</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>none.strict</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.strict</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>MethodDeclaration__1</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(\,)</string>
          <key>name</key>
          <string>punctuation.strict</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([\w\x{003c}\x{003e}]+)(\s+)([a-zA-Z]+[a-zA-Z0-9_]*)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.strict</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>none.strict</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>variable.parameter.strict</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>([\w\x{003c}\x{003e}]+)</string>
          <key>name</key>
          <string>variable.parameter.strict</string>
        </dict>
       </array>
    </dict>
    <key>NumberLiteral</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(\b\d+)</string>
          <key>name</key>
          <string>constant.numeric.strict</string>
        </dict>
       </array>
    </dict>
    <key>Operator</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>([.\x{002b}\x{007c}\-\x{0028}\x{0029}\x{003c}\x{003e}\[\]\x{0021}\x{003d}\x{0025}\x{002a}\x{002c}]+)</string>
          <key>name</key>
          <string>keyword.operator.strict</string>
        </dict>
       </array>
    </dict>
    <key>Statements</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#Loops</string>
        </dict>
       </array>
    </dict>
    <key>TextLiteral</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>(&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.strict</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#TextLiteral__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\&quot;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.strict</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>TextLiteral__1</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(\\(?:\\|&quot;))</string>
          <key>name</key>
          <string>string.strict</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\x{0022}\x{005c}]+)</string>
          <key>name</key>
          <string>string.strict</string>
        </dict>
       </array>
    </dict>
    <key>Throws</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>(throws)(\s+)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.other.strict</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>none.strict</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#Throws__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^(?=.{0,1})(?:|))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>none.strict</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>Throws__1</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>([\w\x{003c}\x{003e}]+)</string>
          <key>name</key>
          <string>entity.name.type.strict</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\,)</string>
          <key>name</key>
          <string>none.strict</string>
        </dict>
       </array>
    </dict>
    <key>TopLevelDeclarations</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#Comment</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#MethodDeclaration</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#Throws</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>

