// Code is generated by the strict compiler.
#ifndef GENERATED_AGE_INPUT_HH_
#define GENERATED_AGE_INPUT_HH_

#include <strict/all.hh>

int main(int argc, char **argv) {

}

#endif // GENERATED_AGE_INPUT_HH_