// Code is generated by the strict compiler.

#include <iostream>
#include <string>
#include <vector>

/* BUILTINS: this will be moved to a separate library soon. */

static int toInt(double number) {
  return (int) number;
}

/* GENERATED CODE */

list<number> divisibleNumbers(number limit) {
	list<number> $yield;
for (auto index = 0; index < limit; index++) {
		if (index % 3 == 0 || index % 5 == 0) {
			$yield.insert(index);
		}
	}
	return $yield;
}

int main(int argc, char **argv) {
	auto numbers = divisibleNumbers(100);
	for (auto element : numbers) {

	}
}
