// Code is generated by the strict compiler.

#include <iostream>
#include <string>
#include <vector>

/* BUILTINS: this will be moved to a separate library soon. */

static int inputNumber(const char *message) {
  puts(message);
  int value;
  scanf("%d", &value);
  return value;
}

/* GENERATED CODE */

std::vector<int> divisibleNumbers(int limit) {
	std::vector<int> $yield;

	for (auto index = 0; index < limit; index++) {
		if (index % 3 == 0 || index % 5 == 0) {
			$yield.push_back(index);
		}
	}
	return $yield;
}

int main(int argc, char **argv) {
	auto numbers = divisibleNumbers(100);
	for (auto element : numbers) {
		printf("%d", toInt(element));
	}
}
