// Code is generated by the strict compiler.

#include <iostream>
#include <string>
#include <vector>

/* BUILTINS: this will be moved to a separate library soon. */

static int inputNumber(const char *message) {
  puts(message);
  int value;
  scanf("%d", &value);
  return value;
}

/* GENERATED CODE */

std::vector<int> range(int begin, int end) {
	std::vector<int> $yield;

	for (auto num = begin; num < end; num++) {
		$yield.push_back(num);
	}
	return $yield;
}

int main(int argc, char **argv) {
	for (auto num : range(1, 21)) {
		if (num % 3 == 0) {
			puts("Fizz");
		}
	}
}
