// Code is generated by the strict compiler.

#include <iostream>
#include <string>
#include <vector>

/* BUILTINS: this will be moved to a separate library soon. */

static int toInt(double number) {
  return (int) number;
}

/* GENERATED CODE */

int main(int argc, char **argv) {
	puts("Hello, World!");
}
