// Code is generated by the strict compiler.

#include <iostream>
#include <string>
#include <vector>

/* BUILTINS: this will be moved to a separate library soon. */

static int inputNumber(const char *message) {
  puts(message);
  int value;
  scanf("%d", &value);
  return value;
}

/* GENERATED CODE */

void doSomething() {

	puts("Hello, World!");
}

int main(int argc, char **argv) {

}
